-- Ensure this session uses utf8mb4
SET NAMES utf8mb4;

-- Fix any garbled Danish characters from a previous latin1 migration run
UPDATE players SET name = 'Carsten Ekstrøm'  WHERE name LIKE 'Carsten Ekstr%m'    AND name != 'Carsten Ekstrøm';
UPDATE players SET name = 'Michael Møller'   WHERE name LIKE 'Michael M%ller'     AND name != 'Michael Møller';
UPDATE players SET name = 'Morten Bjørkmann' WHERE name LIKE 'Morten Bj%rkmann'   AND name != 'Morten Bjørkmann';
UPDATE players SET name = 'Nikke Harkjær'    WHERE name LIKE 'Nikke Harkj%r'      AND name != 'Nikke Harkjær';
UPDATE players SET name = 'Søren Platz'      WHERE name LIKE '%ren Platz'         AND name != 'Søren Platz';
UPDATE players SET name = 'Søren Tetsche'    WHERE name LIKE '%ren Tetsche'       AND name != 'Søren Tetsche';

-- DI setup: players, tournaments, rounds, matches
-- Players
INSERT IGNORE INTO players (name, team) VALUES ('Anders Brandt Larsen', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Anders Trier', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Andrew Merritt', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Anton Jensen', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Carsten Ekstrøm', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Carsten Jepsen', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Christian Holm', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Claus Eland', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Claus Vanggaard', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Danni Lauridsen', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('David Fuglsang', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Dennis Espersen', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Erik Lund', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Flemming Vadet', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('France Chow', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Frank Pedersen', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Henrik Pedersen', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Henrik Wind Pedersen', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Jakob Demant', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Jakob Thomsen', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Jan Guldberg', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Jesper Aasted', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Jesper Bak', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Jesper Brinkmann', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('John Vegner', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Kasper H Jensen', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Kenneth Christensen', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Kim Behrens Jessen', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Kim Damsgaard', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Klaus Thomsen', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Lasse Jakobsen', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Michael Møller', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Michael Trier', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Michael Wermuth', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Morten Bjørkmann', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Nikke Harkjær', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Ole Juhl Rasmussen', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Per Iversen', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Peter Bugge', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Peter Rasmussen', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Peter Uhre', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Preben Martinsen', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Rene Skou Larsen', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Rune Marcussen', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Søren Platz', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Søren Tetsche', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Thomas Bech', 'blue');
INSERT IGNORE INTO players (name, team) VALUES ('Tommy Cawsey', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Torben Nedergaard', 'red');
INSERT IGNORE INTO players (name, team) VALUES ('Torben Sneibjerg', 'red');

-- Tournaments
INSERT IGNORE INTO tournaments (year) VALUES (2019);
INSERT IGNORE INTO tournaments (year) VALUES (2020);
INSERT IGNORE INTO tournaments (year) VALUES (2021);
INSERT IGNORE INTO tournaments (year) VALUES (2022);
INSERT IGNORE INTO tournaments (year) VALUES (2023);
INSERT IGNORE INTO tournaments (year) VALUES (2024);
INSERT IGNORE INTO tournaments (year) VALUES (2025);

-- Rounds (format per round per year)
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 1, 'fourball' FROM tournaments WHERE year=2019;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 2, 'fourball' FROM tournaments WHERE year=2019;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 4, 'singles' FROM tournaments WHERE year=2019;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 1, 'fourball' FROM tournaments WHERE year=2020;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 2, 'fourball' FROM tournaments WHERE year=2020;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 3, 'greensome' FROM tournaments WHERE year=2020;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 4, 'singles' FROM tournaments WHERE year=2020;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 1, 'fourball' FROM tournaments WHERE year=2021;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 2, 'fourball' FROM tournaments WHERE year=2021;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 3, 'greensome' FROM tournaments WHERE year=2021;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 4, 'singles' FROM tournaments WHERE year=2021;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 1, 'fourball' FROM tournaments WHERE year=2022;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 2, 'fourball' FROM tournaments WHERE year=2022;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 3, 'foursome' FROM tournaments WHERE year=2022;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 4, 'singles' FROM tournaments WHERE year=2022;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 1, 'fourball' FROM tournaments WHERE year=2023;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 2, 'fourball' FROM tournaments WHERE year=2023;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 3, 'foursome' FROM tournaments WHERE year=2023;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 4, 'singles' FROM tournaments WHERE year=2023;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 1, 'fourball' FROM tournaments WHERE year=2024;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 2, 'fourball' FROM tournaments WHERE year=2024;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 3, 'foursome' FROM tournaments WHERE year=2024;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 4, 'singles' FROM tournaments WHERE year=2024;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 1, 'fourball' FROM tournaments WHERE year=2025;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 2, 'fourball' FROM tournaments WHERE year=2025;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 3, 'foursome' FROM tournaments WHERE year=2025;
INSERT IGNORE INTO rounds (tournament_id, round_number, format) SELECT id, 4, 'singles' FROM tournaments WHERE year=2025;

-- Matches
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 7 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 8 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 9 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 10 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 11 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 12 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2019 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 7 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 8 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 9 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 10 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 11 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 12 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2020 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 7 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 8 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 9 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 10 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 11 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 12 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2021 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 7 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 8 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 9 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 10 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 11 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 12 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2022 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 7 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 8 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 9 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 10 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2023 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 7 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 8 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 9 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 10 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 11 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 12 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2024 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=1;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=2;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=3;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 1 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 2 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 3 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 4 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 5 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 6 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 7 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 8 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 9 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 10 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 11 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=4;
INSERT IGNORE INTO matches (round_id, match_number) SELECT r.id, 12 FROM rounds r JOIN tournaments t ON t.id=r.tournament_id WHERE t.year=2025 AND r.round_number=4;
